export const GET_INVITATION_CODE_FULFILLED: string = 'GET_INVITATION_CODE_FULFILLED';
export const GET_MY_CLASS_ID_FULFILLED: string = 'GET_MY_CLASS_ID_FULFILLED';
export const TOGGLE_FORGOT_PASSWORD: string = 'TOGGLE_FORGOT_PASSWORD';
export const SIGN_IN_BUFFER_PAGE_ON: string = 'SIGN_IN_BUFFER_PAGE_ON';
export const SIGN_IN_BUFFER_PAGE_OFF: string = 'SIGN_IN_BUFFER_PAGE_OFF';
export const UPDATE_PAGE_TITLE_FULFILLED: string = 'UPDATE_PAGE_TITLE_FULFILLED';
