export const GET_MY_CLASS_STUDENT_ATTEMPT: string = 'GET_MY_CLASS_STUDENT_ATTEMPT';
export const GET_MY_CLASS_STUDENT_FULFILLED: string = 'GET_MY_CLASS_STUDENT_FULFILLED';
export const GET_MY_CLASS_STUDENT_REJECT: string = 'GET_MY_CLASS_STUDENT_REJECT';